export const ADD_CHORE_START = "ADD_CHORE_START";
export const ADD_CHORE_SUCCESS = "ADD_CHORE_SUCCESS";
export const ADD_CHORE_FAIL = "ADD_CHORE_FAIL";

export const GET_CHORE_START = "GET_CHORE_START";
export const GET_CHORE_SUCCESS = "GET_CHORE_SUCCESS";
export const GET_CHORE_FAIL = "GET_CHORE_FAIL";

export const COMPLETE_CHORE_START = "COMPLETE_CHORE_START";
export const COMPLETE_CHORE_SUCCESS = "COMPLETE_CHORE_SUCCESS";
export const COMPLETE_CHORE_FAIL = "COMPLETE_CHORE_FAIL";

export const ADD_WORKOUT_START = "ADD_WORKOUT_START";
export const ADD_WORKOUT_SUCCESS = "ADD_WORKOUT_SUCCESS";
export const ADD_WORKOUT_FAIL = "ADD_WORKOUT_FAIL";

export const GET_WORKOUT_START = "GET_WORKOUT_START";
export const GET_WORKOUT_SUCCESS = "GET_WORKOUT_SUCCESS";
export const GET_WORKOUT_FAIL = "GET_WORKOUT_FAIL";

export const DELETE_WORKOUT_START = "DELETE_WORKOUT_START";
export const DELETE_WORKOUT_SUCCESS = "DELETE_WORKOUT_SUCCESS";
export const DELETE_WORKOUT_FAIL = "DELETE_WORKOUT_FAIL";