export const ADD_BUDGET_START = "ADD_BUDGET_START";
export const ADD_BUDGET_SUCCESS = 'ADD_BUDGET_SUCCESS';
export const ADD_BUDGET_FAIL = 'ADD_BUDGET_FAIL';

export const GET_BUDGET_START = "GET_BUDGET_START";
export const GET_BUDGET_SUCCESS = "GET_BUDGET_SUCCESS";
export const GET_BUDGET_FAIL = "GET_BUDGET_FAIL";

export const SET_BUDGET_START = "SET_BUDGET_START";
export const SET_BUDGET_SUCCESS = "SET_BUDGET_SUCCESS";
export const SET_BUDGET_FAIL = "SET_BUDGET_FAIL";

export const DELETE_BUDGET_START = "DELETE_BUDGET_START";
export const DELETE_BUDGET_SUCCESS = "DELETE_BUDGET_SUCCESS";
export const DELETE_BUDGET_FAIL = "DELETE_BUDGET_FAIL";

export const GET_MAX_START = "GET_MAX_START";
export const GET_MAX_SUCCESS = "GET_MAX_SUCCESS";
export const GET_MAX_FAIL = "GET_MAX_FAIL";

export const RESET_BUDGET_START = "RESET_BUDGET_START";
export const RESET_BUDGET_SUCCESS = "RESET_BUDGET_SUCCESS";
export const RESET_BUDGET_FAIL = "RESET_BUDGET_FAIL";